version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-frontend
    environment:
      - VITE_API_URL=http://localhost:8000/api
    ports:
      - "5173:5173"
    restart: unless-stopped
    